### ISSUE TITLE
can't run auth: TypeError: port must be an integer

### ISSUE THREAD

**Issue by otmezger** [jakubroztocil/geotagger#2]
Hi, 

I'm running python 3.6.5 with anaconda on Mac OS X.

I'm having trouble authenticating. 

```
(base) bash-3.2$ geotagger auth
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/olmo/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/olmo/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/olmo/anaconda3/lib/python3.6/site-packages/geotagger/core.py", line 190, in serve
    app.run(port=settings.WEBAPP_PORT)
  File "/Users/olmo/anaconda3/lib/python3.6/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/Users/olmo/anaconda3/lib/python3.6/site-packages/werkzeug/serving.py", line 748, in run_simple
    raise TypeError('port must be an integer')
TypeError: port must be an integer
```

Any idea what could have gone wrong? 
Happy to provide more info if required.

**Comment by Martin-Downey** [comment]
Hi, I don't program in python. I did see however that the last error message is calling for an integer and you may have a letter.                                                                                                                                     I hope that helps‎ a bit.                                                                                                                                                                                                    Sent from my BlackBerry 10 smartphone on the Virgin Mobile network.                                                                                                                                                                                                                From: Olmo MezgerSent: Saturday, May 26, 2018 15:46To: jakubroztocil/geotaggerReply To: jakubroztocil/geotaggerCc: SubscribedSubject: [jakubroztocil/geotagger] can't run auth: TypeError: port must be an integer (#2)Hi,
I'm running python 3.6.2 with anaconda on Mac OS X.
I'm having trouble authenticating.
(base) bash-3.2$ geotagger auth
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/olmo/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/olmo/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/olmo/anaconda3/lib/python3.6/site-packages/geotagger/core.py", line 190, in serve
    app.run(port=settings.WEBAPP_PORT)
  File "/Users/olmo/anaconda3/lib/python3.6/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/Users/olmo/anaconda3/lib/python3.6/site-packages/werkzeug/serving.py", line 748, in run_simple
    raise TypeError('port must be an integer')
TypeError: port must be an integer

Any idea what could have gone wrong?
Happy to provide more info if required.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/jakubroztocil/geotagger/issues/2","url":"https://github.com/jakubroztocil/geotagger/issues/2","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jakubroztocil/geotagger","title":"jakubroztocil/geotagger","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jakubroztocil/geotagger"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"can't run auth: TypeError: port must be an integer (#2)"}],"action":{"name":"View Issue","url":"https://github.com/jakubroztocil/geotagger/issues/2"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "can't run auth: TypeError: port must be an integer (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Olmo Mezger**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@otmezger",
"facts": [
{
"name": "Repository: ",
"value": "jakubroztocil/geotagger"
},
{
"name": "Issue #: ",
"value": 2
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jakubroztocil/geotagger\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"jakubroztocil/geotagger\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jakubroztocil/geotagger/issues/2"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 339484845\n}"
}
],
"themeColor": "26292E"
}
